### PR TITLE
feat: improve string style list splitting

### PR DESCRIPTION
**Pull request by tmorehouse**
Minor change based on Vue's own style parser https://github.com/vuejs/vue/blob/dev/src/platforms/web/util/style.js#L5-L16

### CODE REVIEW

**Comment by tmorehouse** [comment]
@alexsasharegan I should have added a test in for `background-image: url(https://foo.com/bar?baz;biz;); color: red;`

**Comment by tmorehouse** [comment]
Maybe you could add in a couple of extra tests?

**Comment by tmorehouse** [comment]
Although we know it works :-)

**Comment by alexsasharegan** [comment]
Does this one cover it?
https://github.com/alexsasharegan/vue-functional-data-merge/blob/master/__test__/array-merge.test.ts#L15

**Comment by tmorehouse** [comment]
Yeah that works

**Comment by tmorehouse** [comment]
Although you may want to add a simple style after that, just to make sure it splits any trailing style defs in the string

**Comment by alexsasharegan** [comment]
Got it!

**Comment by alexsasharegan** [comment]
Nice move pulling the regex's from Vue core.

**Comment by tmorehouse** [comment]
I was looking for something else in their utils, and stumbled across the style parser. :)

**Pull request merged**
